# Generated by Django 3.2.4 on 2021-06-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210623_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
